name: cinemapedia
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.4
  flutter_dotenv: ^5.1.0
  dio: ^5.4.3+1
  flutter_riverpod: ^2.5.1
  window_manager: ^0.3.8
  card_swiper: ^3.0.1
  animate_do: ^3.3.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
