name: push_app
description: "A new Flutter project."

publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.4
  flutter_dotenv: ^5.1.0
  dio: ^5.4.3+1
  window_manager: ^0.3.8

  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0

  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner: ^2.4.9
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
